# Generated by Django 6.0.4 on 2026-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
